### ISSUE TITLE
the default private_network start-range (192.168.0) may collide with WIFI network (non-hostonly network)

### ISSUE THREAD

**Issue by solaris10** [scorputty/vagrant-testservers#1]
node.vm.network :private_network, ip: "192.168.0.%d" % (10 + i )

Because WIFI networks often use range 192.168.0, the  vagrant up command may show error: "The specified host network collides with a non-hostonly network! ..."

Easy fix when relevant, change 0 to 10:  "192.168.**10**.%d" % (10 + i )

**Comment by scorputty** [comment]
Hi!
Thanks for pointing this out. I will add state in the readme that the network should be adjusted to specific need. My wifi network for example starts with 172.16 so anything in the 192.168 is no issue.
